version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: remax
    versions:
    - 2.11.7
    - 2.11.8
    - 2.12.0
    - 2.12.1
  - dependency-name: "@apollo/client"
    versions:
    - 3.3.12
    - 3.3.13
    - 3.3.14
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: graphql-tag
    versions:
    - 2.12.2
    - 2.12.3
  - dependency-name: "@tarojs/taro-h5"
    versions:
    - 3.0.25
    - 3.0.26
    - 3.0.27
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@tarojs/taro-weapp"
    versions:
    - 2.2.16
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: regenerator-runtime
    versions:
    - 0.13.7
  - dependency-name: eslint-plugin-typescript
    versions:
    - 0.14.0
  - dependency-name: node-forge
    versions:
    - 0.10.0
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: serialize-javascript
    versions:
    - 2.1.2
